baseURL: "https://blog.danzaii.cn/"
languageCode: "zh-cn"
title: "一只小羊羔的窝"
theme: "hugo-theme-stack"

defaultContentLanguage: "zh-cn"
hasCJKLanguage: true

pagination:
  pagerSize: 10

permalinks:
  post: "/p/:slug/"
  page: "/:slug/"
