social:
  - identifier: github
    name: GitHub
    url: "https://github.com/DanZai233"
    params:
      icon: brand-github

  - identifier: qq
    name: "QQ: 932351233"
    url: "https://wpa.qq.com/msgrd?v=3&uin=932351233&site=qq&menu=yes"
    params:
      icon: brand-qq

  - identifier: netease-music
    name: 网易云音乐
    url: "https://music.163.com/#/user/home?id=75420475"
    params:
      icon: brand-netease-music
      newTab: true

  - identifier: email
    name: "邮箱: danzai233@qq.com"
    url: "mailto:danzai233@qq.com"
    params:
      icon: mail

  - identifier: gallery
    name: 画廊
    url: "https://photo.danzaii.cn"
    params:
      icon: photo
      newTab: true

main:
  - identifier: travellings
    name: 开往
    url: "https://www.travellings.cn/go.html"
    weight: 40
    params:
      icon: train
      newTab: true
