mainSections:
  - post

featuredImageField: "image"
rssFullContent: true

favicon: "img/avatar.png"

footer:
  since: 2025
  customText: ""

dateFormat:
  published: "2006-01-02"
  lastUpdated: "2006-01-02"

sidebar:
  emoji: "ðŸŒ¸"
  subtitle: "è®°å½•ç”Ÿæ´»ï¼Œåˆ†äº«æŠ€æœ¯"
  avatar: "img/avatar.png"
  compact: false

article:
  headingAnchor: true
  math: false
  toc: true
  readingTime: true
  list:
    showTags: true
  license:
    enabled: true
    default: "Licensed under CC BY-NC-SA 4.0"

widgets:
  homepage:
    - type: search
    - type: archives
      params:
        limit: 5
    - type: categories
      params:
        limit: 10
    - type: tag-cloud
      params:
        limit: 10
  page:
    - type: toc

colorScheme:
  toggle: true
  default: "auto"

imageProcessing:
  cover:
    enabled: true
  content:
    enabled: true

comments:
  enabled: false
  provider: ""
